### ISSUE TITLE
dataset not updating after aggregation indicator created

### ISSUE THREAD

**Issue by mberg** [SEL-Columbia/bamboo#372]
For this dataset (grades) new submissions would work

http://bamboo.io/datasets/9d9921ce156340a6a6f163ba0e15b5c3/info

I then added this basic aggregation

[
{
formula: "count()",
state: "ready",
group: "",
name: "num_students"
}
]

Aggregation dataset

http://bamboo.io/datasets/f4e6482690a44005a9bd515737a43427

After adding this aggregate indicator the data **stopped** updating.

Note: in this case eventhough I only used ODK to submit data, the verbal/match switched to string from integer.  Maybe it's related to that, #375.

**Comment by pld** [comment]
@mberg can you retry this?  I think the schema fix should resolve this.

**Comment by mberg** [comment]
No doesn't look like it unfortunately :(

So it verbal/math where brought in properly as integers and the schema
didn't change. Updating worked until I added the calculations

http://bamboo.io/datasets/e6061eb530114979994dfe1c27e99900/calculations

http://bamboo.io/datasets/e6061eb530114979994dfe1c27e99900/info

**Comment by mberg** [comment]
This is still persisting.

Re-ran this scenario and updates stopped working.

curl -X POST -d "name=functional&formula=newest(submit_date,functional)&group=wp_id" http://bamboo.io/calculations/dd2942d7070746b495d3d865f924e827

http://bamboo.io/datasets/dd2942d7070746b495d3d865f924e827

**Comment by pld** [comment]
Until you send an example of update data that's being sent there's no way to fix this.  Try to modify the updates in this test and get it to fail, https://github.com/modilabs/bamboo/blob/master/bamboo/tests/controllers/test_calculations.py#L377

**Comment by mberg** [comment]
I have no idea how to do that. I'm just submitting via formhub.  It should
be exactly the same that is used to create the submissions for the dataset
that I linked.

Not sure what else I can do to help from my end sorry

**Comment by pld** [comment]
From the logs this is a different issue, and from the ds, this has a calculation that conflicts with the datasets original columns see functional column here, http://bamboo.io/datasets/dd2942d7070746b495d3d865f924e827/calculations and here, http://bamboo.io/datasets/dd2942d7070746b495d3d865f924e827/info

Here's a new issue for this, https://github.com/modilabs/bamboo/issues/385

If you don't name the calculation something that overlaps with the dataset's columns this will hopefully work.  If not please reopen and I'll get back at it.

**Comment by pld** [comment]
From the logs this is a different issue, and from the ds, this has a calculation that conflicts with the datasets original columns see functional column here, http://bamboo.io/datasets/dd2942d7070746b495d3d865f924e827/calculations and here, http://bamboo.io/datasets/dd2942d7070746b495d3d865f924e827/info

Here's a new issue for this, https://github.com/modilabs/bamboo/issues/385

If you don't name the calculation something that overlaps with the dataset's columns this will hopefully work.  If not please reopen and I'll get back at it.

**Comment by mberg** [comment]
Ok thanks peter.  Let me check on this a bit more to see what i'm doing
wrong.

**Comment by mberg** [comment]
Should I not be using functional as the name if i'm referencing it in the
formula?

**Comment by prabhasp** [comment]
Inside the formula, you should.
But the name of the new column in the aggregated dataset should be
something different (for now).

prabhas pokharel
skype/twitter/fb: prabhasp
+1 347 9487654

**Comment by pld** [comment]
Correct, but it should also be getting slugged correctly if it's not different, so there is an error in bamboo here, hence the other issue.

**Comment by mberg** [comment]
OK good news.

http://bamboo.io/datasets/a3cb6a3e062c4ad9bae528b61f212904

The dataset continues to update.  Bad news the resultant aggregation
doesn't update.

http://bamboo.io/datasets/22eb79f6fc1c42878a60ceef36b51294

I tried adding the same calculation twice (after a bunch of submissions so
that is why you will see a duplicate aggregation) but the problem existed
before that.

http://bamboo.io/calculations/a3cb6a3e062c4ad9bae528b61f212904

**Comment by pld** [comment]
Cool, a step in the right direction, can you make a new issue for the newest aggregation not updating?  Let's try to close this thread.

**Comment by mberg** [comment]
Will recreate from scratch and then will post
